### PR TITLE
Feature/place system

### LINKED ISSUE #2: Implement an object placement system
The player wants to place machinery on the map

In order to use them

### PR DESCRIPTION
**Pull request by tristepin222**
added a place system

### CODE REVIEW

**Review by VivienCPNV — CHANGES_REQUESTED** [review]
Remove useless exclude lines in project file before merging.

**Review by VivienCPNV — COMMENTED** [review]
Looks good although a few things to double check before merging.
- Does the ObjectPlacerSystem take into account the translation between world position and screen position ? Explanation:
```
Player is at x=10000, y=10000 (in world coordinates).
He tries to place a block at x=125 y=200 (screen coordinates).
Will the block appear at x~=10125 y~=10200 or will is spawn at the world origin ?
```
- Should we really use a [fixed grid size](https://github.com/CPNV-ES/FactorioLike-MAW2.1/blob/9e61dd72ce97c73f9b8453c77fbbc819a3b4b180/MechanoCraft/MechanoCraft.cs#L16) ?
- SpriteRenderer was renamed (this will cause problems when merging with other branches)

**Comment by tristepin222** [comment]
`Mouse.GetState()`

- Returns the mouse position on the windows, there is no translation to world position, it rathers, translate the position into the grid

- Yes, having a fixed grid size poses no problem on the scope of our project, if let's says, we add bigger machines, this isn't the code to manage how big is an entity, the process to create assets for the game need to be standardised

Explanation :

For now, each machines takes one space in the grid, let's say i want to make a machine that takes 2x2 spaces, i will have to make the sprite visually 2x2 in the grid, so it would be 2 times bigger than the ones that takes one space only

the only thing that needs to be implement is a way to prevent a 1x1 machine to be added into a 2x2 machine space, but since this isn't the scope of the project, i think this doesn't need to be implemented, yet

- as far as i can see, the merge has no conflicts

**Review by VivienCPNV — APPROVED** [review]
Looks ok, although keep in mind that.
SpriteRenderer being renamed to SpriteRendererSystem will surely cause problems in future merges (SpriteRender might show up twice and be called twice).

**Pull request merged**
